// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.
#include<iostream>
#include<unordered_set>
using namespace std;

char findExtra(string s, string t){
    unordered_set<char> seen;
    for(char ch : s){
        seen.insert(ch);
    }

    char target;
    for(char c : t){
        if(!(seen.count(c))){
            target = c;
            break;
        }
    }
    return target;
}

int main()
{
    string s, t;
    cin>>s>>t;
    cout<< findExtra(s, t);
    return 0;
}